-- ---------------------------------------------------------------------------
-- Let the swap cache survive a better prompt.
--
-- 0033 keyed item_swaps on (term, locale), which is right for a cache whose
-- answers never change — and wrong for this one, because the answers are a
-- MODEL's and the prompt that shapes them is code we improve. The first
-- improvement proved it: the original prompt's only worked example was beef
-- mince, so it suggested mince for whatever was asked, including a steak. Fixing
-- the prompt did nothing for anybody whose row was already cached, and there was
-- no way to say "that answer came from the old instructions" short of deleting
-- rows by hand.
--
-- So the prompt's version joins the key. A bump makes every existing row invisible
-- to the function instead of wrong-but-served: the next reader misses the cache,
-- asks once, and warms a new row beside the old one. No deletion, no downtime,
-- and the old rows stay readable for comparison if a change turns out worse.
--
-- The alternative — clearing the table on each prompt change — throws away every
-- warm answer at the moment of highest traffic, which is exactly when the cache
-- is worth most.
-- ---------------------------------------------------------------------------

alter table item_swaps
  add column if not exists prompt_version integer not null default 1;

-- Existing rows keep 1, which is truthful: they were generated by prompt 1. The
-- function now asks for its own current version, so they simply stop being
-- served the moment it moves past 1.

-- The key becomes (term, locale, prompt_version) so answers from different
-- prompts coexist. Dropped by looked-up name rather than a guessed one, for the
-- same reason as 0031: a database restored through a tool that renames
-- constraints would otherwise fail here rather than in review.
do $$
declare
  c text;
begin
  select conname into c
  from pg_constraint
  where conrelid = 'item_swaps'::regclass and contype = 'p';

  if c is not null then
    execute format('alter table item_swaps drop constraint %I', c);
  end if;
end $$;

alter table item_swaps
  add primary key (term, locale, prompt_version);

-- No extra index: every read is still an exact three-column lookup, which the
-- new primary key serves.
